# Generated by Django 5.1.5 on 2025-01-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(db_column='Description', max_length=10000, verbose_name='Описание')),
                ('image_event', models.ImageField(blank=True, db_column='Image_event', default=None, null=True, upload_to='fpga/images/%Y/%m/%d/', verbose_name='Фотография события')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'db_table': 'PhotoEvent',
            },
        ),
        migrations.CreateModel(
            name='ProjectsFpga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=80, verbose_name='Название проекта')),
                ('description', models.TextField(db_column='Description', max_length=10000, verbose_name='Описание')),
                ('link_gh', models.TextField(blank=True, db_column='Link_Gh', default=None, max_length=250, null=True, verbose_name='Ссылка на GitHub')),
                ('link_yb', models.TextField(blank=True, db_column='Link_Yb', default=None, max_length=250, null=True, verbose_name='Ссылка на Youtube')),
                ('link_web', models.TextField(blank=True, db_column='Link_Web', default=None, max_length=250, null=True, verbose_name='Ссылка на Web-сайт')),
                ('image_1', models.ImageField(blank=True, db_column='Image_1', default=None, null=True, upload_to='fpga/images/%Y/%m/%d/', verbose_name='Изображение_1')),
                ('image_2', models.ImageField(blank=True, db_column='Image_2', default=None, null=True, upload_to='fpga/images/%Y/%m/%d/', verbose_name='Изображение_3')),
                ('image_3', models.ImageField(blank=True, db_column='Image_3', default=None, null=True, upload_to='fpga/images/%Y/%m/%d/', verbose_name='Изображение_3')),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_column='UploadDate', verbose_name='Дата создания')),
                ('autor', models.TextField(blank=True, db_column='Autor', default=None, max_length=250, null=True, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'ProjectFPGA',
            },
        ),
    ]
