# Generated by Django 5.1.5 on 2025-02-03 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoevent',
            name='upload_date_event',
            field=models.DateTimeField(auto_now_add=True, db_column='UploadDate', default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
